#ifndef RAW_INPUT_CONSTANTS_SHARDLITE
#define RAW_INPUT_CONSTANTS_SHARDLITE

enum RawInput
{
	INVALID,

	INPUT_SCANCODE_A = 4,
	INPUT_SCANCODE_B = 5,
	INPUT_SCANCODE_C = 6,
	INPUT_SCANCODE_D = 7,
	INPUT_SCANCODE_E = 8,
	INPUT_SCANCODE_F = 9,
	INPUT_SCANCODE_G = 10,
	INPUT_SCANCODE_H = 11,
	INPUT_SCANCODE_I = 12,
	INPUT_SCANCODE_J = 13,
	INPUT_SCANCODE_K = 14,
	INPUT_SCANCODE_L = 15,
	INPUT_SCANCODE_M = 16,
	INPUT_SCANCODE_N = 17,
	INPUT_SCANCODE_O = 18,
	INPUT_SCANCODE_P = 19,
	INPUT_SCANCODE_Q = 20,
	INPUT_SCANCODE_R = 21,
	INPUT_SCANCODE_S = 22,
	INPUT_SCANCODE_T = 23,
	INPUT_SCANCODE_U = 24,
	INPUT_SCANCODE_V = 25,
	INPUT_SCANCODE_W = 26,
	INPUT_SCANCODE_X = 27,
	INPUT_SCANCODE_Y = 28,
	INPUT_SCANCODE_Z = 29,

	INPUT_SCANCODE_1 = 30,
	INPUT_SCANCODE_2 = 31,
	INPUT_SCANCODE_3 = 32,
	INPUT_SCANCODE_4 = 33,
	INPUT_SCANCODE_5 = 34,
	INPUT_SCANCODE_6 = 35,
	INPUT_SCANCODE_7 = 36,
	INPUT_SCANCODE_8 = 37,
	INPUT_SCANCODE_9 = 38,
	INPUT_SCANCODE_0 = 39,

	INPUT_SCANCODE_RETURN = 40,
	INPUT_SCANCODE_ESCAPE = 41,
	INPUT_SCANCODE_BACKSPACE = 42,
	INPUT_SCANCODE_TAB = 43,
	INPUT_SCANCODE_SPACE = 44,

	INPUT_SCANCODE_MINUS = 45,
	INPUT_SCANCODE_EQUALS = 46,
	INPUT_SCANCODE_LEFTBRACKET = 47,
	INPUT_SCANCODE_RIGHTBRACKET = 48,
	INPUT_SCANCODE_BACKSLASH = 49,
	INPUT_SCANCODE_NONUSHASH = 50,

	INPUT_SCANCODE_SEMICOLON = 51,
	INPUT_SCANCODE_APOSTROPHE = 52,
	INPUT_SCANCODE_GRAVE = 53,

	INPUT_SCANCODE_COMMA = 54,
	INPUT_SCANCODE_PERIOD = 55,
	INPUT_SCANCODE_SLASH = 56,

	INPUT_SCANCODE_CAPSLOCK = 57,

	INPUT_SCANCODE_F1 = 58,
	INPUT_SCANCODE_F2 = 59,
	INPUT_SCANCODE_F3 = 60,
	INPUT_SCANCODE_F4 = 61,
	INPUT_SCANCODE_F5 = 62,
	INPUT_SCANCODE_F6 = 63,
	INPUT_SCANCODE_F7 = 64,
	INPUT_SCANCODE_F8 = 65,
	INPUT_SCANCODE_F9 = 66,
	INPUT_SCANCODE_F10 = 67,
	INPUT_SCANCODE_F11 = 68,
	INPUT_SCANCODE_F12 = 69,

	INPUT_SCANCODE_PRINTSCREEN = 70,
	INPUT_SCANCODE_SCROLLLOCK = 71,
	INPUT_SCANCODE_PAUSE = 72,
	INPUT_SCANCODE_INSERT = 73,

	INPUT_SCANCODE_HOME = 74,
	INPUT_SCANCODE_PAGEUP = 75,
	INPUT_SCANCODE_DELETE = 76,
	INPUT_SCANCODE_END = 77,
	INPUT_SCANCODE_PAGEDOWN = 78,
	INPUT_SCANCODE_RIGHT = 79,
	INPUT_SCANCODE_LEFT = 80,
	INPUT_SCANCODE_DOWN = 81,
	INPUT_SCANCODE_UP = 82,

	INPUT_LEFT_CLICK_PRESS,
	INPUT_LEFT_CLICK_RELEASE,
	INPUT_RIGHT_CLICK_PRESS,
	INPUT_RIGHT_CLICK_RELEASE,
	INPUT_MIDDLE_CLICK_PRESS,
	INPUT_MIDDLE_CLICK_RELEASE,

	INPUT_MOUSE_MOTION,

	NUM_EVENTS
};

#endif